name: urban_aura_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  dio: ^5.4.1
  flutter_secure_storage: ^9.2.2
  vector_graphics: ^1.1.11+1
  vector_graphics_compiler: ^1.1.11+1
  flutter_animate: ^4.5.0
  equatable: ^2.0.5
  faker: ^2.1.0
  firebase_core: ^3.2.0
  fpdart: ^1.1.0
  cached_network_image: ^3.3.1
  rxdart: ^0.28.0
  algolia_helper_flutter: ^1.1.0
  sliver_tools: ^0.2.12
  flutter_stripe: ^11.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
     - assets/images/
     - assets/icons/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
