// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDOGwboW34eSyaQ0kEFe0XBaqVdIUyOyE',
    appId: '1:1037376833956:web:5a582cdd9df4aaab831931',
    messagingSenderId: '1037376833956',
    projectId: 'urban-aura-4cd33',
    authDomain: 'urban-aura-4cd33.firebaseapp.com',
    storageBucket: 'urban-aura-4cd33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByOqIHVIbm5rYM75NqazO7Tv81NWO6V6o',
    appId: '1:1037376833956:android:a051b84c30f8a6cf831931',
    messagingSenderId: '1037376833956',
    projectId: 'urban-aura-4cd33',
    storageBucket: 'urban-aura-4cd33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACYs3uc71kzCPupPZgN8PuIYzTIfupas',
    appId: '1:1037376833956:ios:534aec5daa060688831931',
    messagingSenderId: '1037376833956',
    projectId: 'urban-aura-4cd33',
    storageBucket: 'urban-aura-4cd33.appspot.com',
    iosBundleId: 'com.sameer.urbanAuraFlutter',
  );
}
