// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCveuQf-AR0wWYWVBIMbZCiANmuUDJJnJw',
    appId: '1:447651406966:web:d81bcc9d1b3d45035ceb57',
    messagingSenderId: '447651406966',
    projectId: 'urban-aura-209c9',
    authDomain: 'urban-aura-209c9.firebaseapp.com',
    storageBucket: 'urban-aura-209c9.appspot.com',
    measurementId: 'G-3CQBZLZTRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByR1y-hmIsbrwhTn6Wd0P-TAHIil9gmtE',
    appId: '1:447651406966:android:70cfdfad068cbcd15ceb57',
    messagingSenderId: '447651406966',
    projectId: 'urban-aura-209c9',
    storageBucket: 'urban-aura-209c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbL45eo8fxterJd-Z0p2QiBBofNE8BX9U',
    appId: '1:447651406966:ios:04e2ee7e37a936225ceb57',
    messagingSenderId: '447651406966',
    projectId: 'urban-aura-209c9',
    storageBucket: 'urban-aura-209c9.appspot.com',
    iosBundleId: 'com.sameer.urbanAuraFlutter',
  );
}
